#!/bin/sh

alpha='dd'
background='#3c3836'
selection='#504945'
comment='#6272a4'

yellow='#ebdbb2'
orange='#fe8019'
red='#fb4934'
magenta='#d3869b'
blue='#83a598'
cyan='#d3869b'
green='#b8bb26'


i3lock \
  --insidever-color=$selection \
  --insidewrong-color=$background \
  --inside-color=$selection \
  --ringver-color=$magenta \
  --ringwrong-color=$red \
  --ringver-color=$magenta \
  --ringwrong-color=$red\
  --ring-color=$background \
  --line-uses-ring \
  --keyhl-color=$cyan \
  --bshl-color=$orange \
  --separator-color=$selection \
  --verif-color=$magenta \
  --wrong-color=$red \
  --layout-color=$blue \
  --date-color=$selection \
  --time-color=$yellow \
  --screen 2 \
  --blur 17 \
  --clock \
  --indicator \
  --time-str="%I:%M" \
  --verif-text="Checking" \
  --wrong-text="Wrong Input" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --radius=120 \
  --ring-width=16 \
  --pass-media-keys \
  --pass-volume-keys \
  --nofork \
  --show-failed-attempts \
  --image /usr/share/backgrounds/gruvbox/irl/beachdual3.jpg \
  --time-font="JetBrainsMono Nerd Font" \
  --date-font="JetBrainsMono Nerd Font" \
  --layout-font="JetBrainsMono Nerd Font" \
  --verif-font="JetBrainsMono Nerd Font" \
  --wrong-font="JetBrainsMono Nerd Font" \
  \

# eww -c $HOME/.config/eww open greeter
# eww -c $HOME/.config/eww/ close-all && eww -c $HOME/.config/eww/ open profile && sleep 0.8 && eww -c $HOME/.config/eww/ close-all

